"use strict";
(() => {
  let api, bootstrap, selectedReport, selectedWorkbook, taskId, findings=[], selectedIds=[], period="", commitToken, pollTimer;
  let startBusy=false, pollGeneration=0, previewGeneration=0, selectedFindingId=null, controlsLoaded=false, controlsByFinding={};
  let previewBusy=false, workbookGeneration=0, controlsWorkbookToken=null;
  let riskCatalog=[], ownerDeptByFinding={}, remediationByFinding={};
  const $=id=>document.getElementById(id);
  const dims=["imp_financial","imp_compliance","imp_operation","imp_reputation","imp_fraud","imp_strategy","imp_data","imp_hse"];
  const terminal=new Set(["待复核","已完成","失败"]);
  const approved=["title","fact_summary","source_page","source_excerpt","matched_risk_id","domain","likelihood",...dims,"rationale","needs_review","review_status"];
  function message(text,error=false){const el=$("report-status");el.textContent=text;el.className="report-status"+(error?" report-error":"");}
  function safeError(error){const code=error?.code||"";if(code==="SOURCE_RESELECT_REQUIRED"||code==="SOURCE_HASH_CHANGED")return "原始报告不可用或已变更，请重新选择报告。";if(code.startsWith("WORKBOOK_"))return "正式工作簿不可用、已变更或与分析任务不匹配，请重新开始分析。";if(code.startsWith("MODEL_")||code==="MODEL")return "模型配置尚未验证或连接不可用，请保存并重新测试。";if(code==="PREVIEW_REQUIRED"||code==="STALE")return "提交预览已失效，请重新生成预览。";if(code==="OUTPUT_EXISTS")return "输出文件已存在，请调整输出后重试。";return "操作未完成，请检查输入后重试。";}
  async function call(name,...args){try{const value=await api[name](...args);if(value&&value.ok===false)throw value;return value?.ok===true?Object.fromEntries(Object.entries(value).filter(([key])=>key!=="ok")):value;}catch(error){message(safeError(error),true);throw error;}}
  function step(number){["upload","extract","review","commit"].forEach((name,index)=>{const el=$("report-step-"+name);el.hidden=index+1!==number;$("report-tab-"+name).setAttribute("aria-current",index+1===number?"step":"false");});}
  function profileOptions(){const profiles=bootstrap?.profiles||[];$("report-model-profile").innerHTML=profiles.map(p=>`<option value="${esc(p.name)}">${esc(p.name)} · ${esc(p.model)}</option>`).join("");const domain=document.querySelector('[data-finding-field="domain"]');domain.innerHTML=(bootstrap?.domains||[]).map(item=>`<option value="${esc(item)}">${esc(item)}</option>`).join("");}
  function profileDetails(){const profile=(bootstrap?.profiles||[]).find(item=>item.name===$("report-model-profile").value);$("report-model-summary").textContent=profile?`模型：${profile.name} / ${profile.model}；目标主机：${new URL(profile.base_url).hostname}`:"请选择已保存的模型配置";}
  function resetCommitState(){controlsLoaded=false;controlsWorkbookToken=null;controlsByFinding={};commitToken=null;$("report-controls-confirmed").checked=false;$("report-change-preview").hidden=true;renderCurrentControls();}
  async function chooseReport(){pollGeneration++;clearTimeout(pollTimer);startBusy=false;$("report-start").disabled=false;const item=await call("choose_report","report");selectedReport=item.selection_token;resetCommitState();$("report-file-name").textContent=`已选择：${item.basename}`;message("请选择正式工作簿、评估期间并验证模型后开始分析。");}
  async function chooseWorkbook(){const generation=++workbookGeneration;const item=await call("choose_report","workbook");if(generation!==workbookGeneration)return;selectedWorkbook=item.selection_token;resetCommitState();$("report-workbook-name").textContent=`已选择：${item.basename}`;message("正式工作簿已选择；分析和提交将绑定此文件。");}
  async function saveProfile(){const profile={name:$("model-name").value.trim(),base_url:$("model-base-url").value.trim(),model:$("model-model").value.trim(),api_key:$("model-api-key").value,supports_vision:$("model-supports-vision").checked};const saved=await call("save_model_profile",profile);$("model-api-key").value="";bootstrap.profiles=(bootstrap.profiles||[]).filter(p=>p.name!==saved.profile.name).concat(saved.profile);profileOptions();$("report-model-profile").value=saved.profile.name;profileDetails();message("模型配置已保存；密钥不会再次显示。");}
  async function testProfile(){const result=await call("test_model_profile",$("report-model-profile").value);message(`模型连接已验证：${result.hostname}`);}
  async function start(){if(startBusy)return;period=$("report-period").value.trim();if(!selectedReport||!selectedWorkbook||!/^[A-Za-z0-9][A-Za-z0-9_-]{0,31}$/.test(period)){message("请先选择报告和正式工作簿，并填写安全的评估期间。",true);return;}startBusy=true;$("report-start").disabled=true;const generation=++pollGeneration;clearTimeout(pollTimer);try{const result=await call("start_analysis",selectedReport,selectedWorkbook,period,$("report-model-profile").value);if(generation!==pollGeneration)return;riskCatalog=result.risk_catalog||[];ownerDeptByFinding={};remediationByFinding={};const localTaskId=result.task.task_id;taskId=localTaskId;$("report-extraction-method").textContent=`提取方式：${result.task.extraction_method||"本地处理"}`;step(2);await poll(localTaskId,generation);}catch(_){if(generation===pollGeneration){startBusy=false;$("report-start").disabled=false;}}}
  async function poll(localTaskId,generation){if(generation!==pollGeneration)return;try{const result=await call("get_task",localTaskId);if(generation!==pollGeneration)return;const task=result.task;$("report-extraction-method").textContent=`状态：${task.status}；提取方式：${task.extraction_method||"本地处理"}`;if(terminal.has(task.status)){clearTimeout(pollTimer);if(task.status==="失败"){pollGeneration++;startBusy=false;$("report-start").disabled=false;message("本地提取失败，可重新选择报告后重试。",true);return;}const localFindings=(await call("get_findings",localTaskId)).findings||[];if(generation!==pollGeneration)return;findings=localFindings;pollGeneration++;startBusy=false;renderFindings();step(3);message(`已提取 ${findings.length} 项合成发现；模型输出仅供审计判断参考。`);return;}pollTimer=setTimeout(()=>poll(localTaskId,generation).catch(()=>{}),750);}catch(_){if(generation===pollGeneration){startBusy=false;$("report-start").disabled=false;}}}
  function value(f,key){if(key==="needs_review")return f.needs_review?"true":"false";if(dims.includes(key))return f.impact_scores?.[key]??"";return f[key]??"";}
  function formValue(){const payload={impact_scores:{}};approved.forEach(key=>{const input=document.querySelector(`[data-finding-field="${key}"]`);let fieldValue=input?.type==="checkbox"?input.checked:input?.value;if(dims.includes(key)){payload.impact_scores[key]=fieldValue===""?null:Number(fieldValue);return;}if(key==="likelihood")fieldValue=fieldValue===""?null:Number(fieldValue);if(key==="needs_review")fieldValue=Boolean(fieldValue);payload[key]=fieldValue;});return payload;}
  function fillForm(f){approved.forEach(key=>{const input=document.querySelector(`[data-finding-field="${key}"]`);if(!input)return;if(input.type==="checkbox")input.checked=Boolean(f[key]);else input.value=value(f,key);});$("report-finding-form").__findingId=f.finding_id;}
  function renderFindings(){const list=$("report-findings");list.innerHTML=findings.map(f=>`<button type="button" class="report-finding" data-finding-id="${esc(f.finding_id)}" aria-selected="${selectedIds.includes(f.finding_id)}">${esc(f.finding_id)} · ${esc(f.title)} <span class="note">${f.merged_into?`已合并至 ${esc(f.merged_into)}`:esc(f.review_status)}</span></button>`).join("");list.querySelectorAll("[data-finding-id]").forEach(button=>button.addEventListener("click",event=>selectFinding(button.dataset.findingId,event.ctrlKey||event.metaKey)));if(findings.length&&!$("report-finding-form").__findingId)selectFinding(findings[0].finding_id,false);}
  async function selectFinding(id,multi){if(multi){selectedIds=selectedIds.includes(id)?selectedIds.filter(item=>item!==id):[...selectedIds,id];renderFindings();return;}selectedIds=[id];selectedFindingId=id;const generation=++previewGeneration;const finding=findings.find(item=>item.finding_id===id);fillForm(finding);renderFindings();try{const preview=await call("get_source_preview",taskId,id,selectedReport);if(generation!==previewGeneration||selectedFindingId!==id)return;const viewer=$("report-source-viewer");viewer.replaceChildren();if(preview.kind==="pdf"&&typeof preview.image_data_url==="string"){const image=document.createElement("img");image.src=preview.image_data_url;image.alt=`来源页 ${preview.source_page||""}`;image.style.maxWidth="100%";viewer.append(image);}else viewer.textContent=preview.source_excerpt||"来源预览不可用";}catch(_){if(generation===previewGeneration&&selectedFindingId===id)$("report-source-viewer").textContent="请重新选择报告以查看来源。";}}
  function patchFindings(items){const values=items?.findings||(items?.finding?[items.finding]:[]);values.forEach(item=>{const index=findings.findIndex(current=>current.finding_id===item.finding_id);if(index>=0)findings[index]=item;else findings.push(item);});}
  function replaceSaved(items){patchFindings(items);$("report-finding-form").__findingId="";renderFindings();}
  async function saveFinding(status){const id=$("report-finding-form").__findingId;if(!id)return;const payload=formValue();payload.review_status=status||payload.review_status;const result=await call("save_finding",taskId,id,payload);replaceSaved(result);message("发现已保存，仍需审计人员判断。");}
  async function merge(){if(selectedIds.length<2){message("请选择至少两项发现后合并。",true);return;}const result=await call("merge_findings",taskId,selectedIds,formValue());patchFindings(result);selectedIds=[selectedIds[0]];renderFindings();message("所选发现已合并；全部来源证据仍保留并关联到主发现。");}
  async function split(){const id=$("report-finding-form").__findingId;if(!id)return;const base=formValue();const payloads=[{...base,finding_id:`${id}-A`},{...base,finding_id:`${id}-B`,title:`${base.title}（拆分）`}];const result=await call("split_finding",taskId,id,payloads);patchFindings(result);renderFindings();}
  function primaryFindings(){return findings.filter(f=>!f.merged_into);}
  function defaultOwner(f){if(!f.matched_risk_id)return "";const matches=riskCatalog.filter(r=>r.risk_id===f.matched_risk_id);return (matches.find(r=>r.period===period)||matches[matches.length-1]||{}).owner_dept||"";}
  function ensureDecisionDefaults(f){if(ownerDeptByFinding[f.finding_id]===undefined)ownerDeptByFinding[f.finding_id]=defaultOwner(f);if(remediationByFinding[f.finding_id]===undefined)remediationByFinding[f.finding_id]="未确认";}
  function decisionKey(f){return [f.finding_id,...(f.merged_finding_ids||[])].join("|");}
  function invalidateDecision(){commitToken=null;$("report-change-preview").hidden=true;$("report-controls-confirmed").checked=false;}
  function renderRiskDecisions(){const container=$("report-risk-decisions");container.replaceChildren();primaryFindings().filter(f=>f.review_status!=="已排除").forEach(f=>{ensureDecisionDefaults(f);const group=document.createElement("section"),title=document.createElement("h4"),ownerLabel=document.createElement("label"),owner=document.createElement("input"),statusLabel=document.createElement("label"),status=document.createElement("select");title.textContent=`发现 ${decisionKey(f)} 的正式风险确认`;ownerLabel.textContent="责任部门";owner.type="text";owner.value=ownerDeptByFinding[f.finding_id];owner.setAttribute("aria-label",`责任部门 ${f.finding_id}`);owner.addEventListener("input",()=>{ownerDeptByFinding[f.finding_id]=owner.value;invalidateDecision();});statusLabel.textContent="整改状态";status.setAttribute("aria-label",`整改状态 ${f.finding_id}`);["未确认","未整改","整改中","已整改","不适用"].forEach(value=>{const option=document.createElement("option");option.value=value;option.textContent=value;option.selected=remediationByFinding[f.finding_id]===value;status.append(option);});status.addEventListener("change",()=>{remediationByFinding[f.finding_id]=status.value;invalidateDecision();});ownerLabel.append(owner);statusLabel.append(status);group.append(title,ownerLabel,statusLabel);container.append(group);});}
  function decisions(includeControls=false){if(primaryFindings().some(f=>f.review_status==="待确认"))throw new Error("PENDING_REVIEW");return primaryFindings().map(f=>{if(f.review_status==="已排除")return {action:"exclude",finding_ids:[f.finding_id]};ensureDecisionDefaults(f);if(!ownerDeptByFinding[f.finding_id].trim())throw new Error("OWNER_REQUIRED");if(remediationByFinding[f.finding_id]==="未确认")throw new Error("REMEDIATION_REQUIRED");const finding_ids=[f.finding_id,...(f.merged_finding_ids||[])];const result={action:f.matched_risk_id?"merge":"create",finding_ids,risk_id:f.matched_risk_id||"",name:f.title,domain:f.domain,description:f.fact_summary,owner_dept:ownerDeptByFinding[f.finding_id].trim(),period,likelihood:f.likelihood,impact_scores:f.impact_scores,rationale:f.rationale,remediation_status:remediationByFinding[f.finding_id]};if(includeControls)result.controls=(controlsByFinding[finding_ids.join("|")]||[]).map(control=>({description:control.description,score:Number(control.score),key:Boolean(control.key)}));return result;});}
  function controlIdentities(){return decisions(false).filter(item=>item.action!=="exclude").map(({finding_ids,action,risk_id,period:decisionPeriod})=>({finding_ids,action,risk_id,period:decisionPeriod}));}
  function editControls(id,controls){controlsByFinding[id]=controls;$("report-controls-confirmed").checked=false;renderCurrentControls();}
  function renderCurrentControls(){const container=$("report-current-controls");container.replaceChildren();if(!controlsLoaded)return;Object.entries(controlsByFinding).forEach(([id,controls])=>{const group=document.createElement("section"),title=document.createElement("h4");title.textContent=`发现 ${id} 的确认控制点`;group.append(title);controls.forEach((control,index)=>{const row=document.createElement("div");row.className="frow";const description=document.createElement("input");description.type="text";description.value=control.description;description.setAttribute("aria-label",`控制点 ${id}`);description.addEventListener("change",()=>{const next=[...controls];next[index]={...next[index],description:description.value};editControls(id,next);});const score=document.createElement("select");[1,2,3,4,5].forEach(number=>{const option=document.createElement("option");option.value=String(number);option.textContent=String(number);option.selected=Number(control.score)===number;score.append(option);});score.addEventListener("change",()=>{const next=[...controls];next[index]={...next[index],score:Number(score.value)};editControls(id,next);});const key=document.createElement("input");key.type="checkbox";key.checked=Boolean(control.key);key.setAttribute("aria-label",`关键控制 ${id}`);key.addEventListener("change",()=>{const next=[...controls];next[index]={...next[index],key:key.checked};editControls(id,next);});const remove=document.createElement("button");remove.type="button";remove.className="btn sm";remove.textContent="移除";remove.addEventListener("click",()=>editControls(id,controls.filter((_,itemIndex)=>itemIndex!==index)));row.append(description,score,key,remove);group.append(row);});const add=document.createElement("button");add.type="button";add.className="btn sm";add.textContent="添加控制点";add.addEventListener("click",()=>editControls(id,[...controls,{description:"",score:3,key:false}]));group.append(add);container.append(group);});}
  function applyLoadedControls(groups,token){controlsByFinding={};(groups||[]).forEach(group=>{controlsByFinding[group.finding_ids.join("|")]=(group.controls||[]).map(control=>({description:control.description,score:control.score,key:Boolean(control.key)}));});controlsLoaded=true;controlsWorkbookToken=token;renderCurrentControls();}
  function renderPreview(preview){const fields=["new_risks","updated_risks","new_controls","excluded_count","warnings"];$("report-preview-list").innerHTML=fields.map(key=>`<li>${key}：${esc(JSON.stringify(preview[key]??[]))}</li>`).join("");$("report-change-preview").hidden=false;}
  async function preview(){if(previewBusy)return;try{decisions(false);}catch(_){message("请先接受或排除全部发现，并确认责任部门与整改状态。",true);return;}previewBusy=true;const button=$("report-preview");button.disabled=true;try{if(!selectedWorkbook){message("正式工作簿未绑定，请重新开始分析。",true);return;}if(!controlsLoaded||controlsWorkbookToken!==selectedWorkbook){const generation=workbookGeneration;const token=selectedWorkbook;const loaded=await call("preview_commit",taskId,token,period,controlIdentities(),"load_controls");if(generation!==workbookGeneration||token!==selectedWorkbook)return;applyLoadedControls(loaded.controls_by_decision,token);message("已载入当前控制点，请编辑并明确确认后再生成预览。");return;}if(controlsWorkbookToken!==selectedWorkbook){controlsLoaded=false;message("工作簿已变更，请重新开始分析。",true);return;}const controls_confirmed=$("report-controls-confirmed").checked;if(!controls_confirmed){message("请确认已显示的当前控制点。",true);return;}const result=await call("preview_commit",taskId,selectedWorkbook,period,decisions(true),"preview",controls_confirmed);if(controlsWorkbookToken!==selectedWorkbook)return;commitToken=result.commit_token;renderPreview(result);message("预览已生成。历史发现不证明当前剩余风险，提交前请复核。");}finally{previewBusy=false;button.disabled=false;}}
  async function commit(){if(!commitToken)return;const button=$("report-commit");button.disabled=true;let workbookCommitted=false;try{const result=await call("commit_to_workbook",taskId,selectedWorkbook,period,decisions(true),commitToken);workbookCommitted=true;commitToken=null;$("report-output-path").textContent=`已写入：${result.workbook_path}`;const period_data=result.period_data;if(!period_data||!window.RAHMDesktop.loadPeriodData(period_data.period,period_data.risks,period_data.controls))throw new Error("PERIOD_DATA_INVALID");message(`已写入：${result.workbook_path}`);document.querySelector("main").scrollIntoView({behavior:"smooth"});}catch(_){if(!workbookCommitted)button.disabled=false;else message("工作簿已写入，但页面数据加载失败；请重新打开输出文件核对。",true);}}
  async function init(){api=window.pywebview&&window.pywebview.api;if(!api)return;bootstrap=await call("get_bootstrap");$("desktop-report-nav").hidden=false;$("desktop-report-nav").addEventListener("click",()=>{$("desktop-report-shell").hidden=false;step(1);});profileOptions();profileDetails();$("report-model-profile").addEventListener("change",profileDetails);$("report-choose").addEventListener("click",()=>chooseReport().catch(()=>{}));$("report-choose-workbook").addEventListener("click",()=>chooseWorkbook().catch(()=>{}));$("report-start").addEventListener("click",()=>start().catch(()=>{}));$("model-save").addEventListener("click",()=>saveProfile().catch(()=>{}));$("model-test").addEventListener("click",()=>testProfile().catch(()=>{}));$("report-save").addEventListener("click",()=>saveFinding().catch(()=>{}));$("report-accept").addEventListener("click",()=>saveFinding("已接受").catch(()=>{}));$("report-exclude").addEventListener("click",()=>saveFinding("已排除").catch(()=>{}));$("report-merge").addEventListener("click",()=>merge().catch(()=>{}));$("report-split").addEventListener("click",()=>split().catch(()=>{}));$("report-to-commit").addEventListener("click",()=>{renderRiskDecisions();step(4);});$("report-preview").addEventListener("click",()=>preview().catch(()=>{}));$("report-commit").addEventListener("click",()=>commit().catch(()=>{}));}
  window.addEventListener("pywebviewready",()=>init().catch(()=>{}),{once:true});
})();
