"use strict";
(() => {
  let api, bootstrap, selectedReport, selectedWorkbook, taskId, findings = [], selectedIds = [], period = "", commitToken, pollTimer;
  const $ = id => document.getElementById(id);
  const dims = ["imp_financial","imp_compliance","imp_operation","imp_reputation","imp_fraud","imp_strategy","imp_data","imp_hse"];
  const labels = {imp_financial:"经济损失",imp_compliance:"合规法律",imp_operation:"运营中断",imp_reputation:"声誉舆情",imp_fraud:"舞弊风险",imp_strategy:"战略影响",imp_data:"数据安全",imp_hse:"健康安全"};
  const terminal = new Set(["待复核","已完成","失败"]);
  const approved = ["title","fact_summary","source_page","source_excerpt","matched_risk_id","domain","likelihood",...dims,"rationale","needs_review","review_status"];
  function message(text, error=false){const el=$("report-status"); el.textContent=text; el.className="report-status"+(error?" report-error":"");}
  function safeError(error){const code=error?.code || ""; if(code === "SOURCE_RESELECT_REQUIRED" || code === "SOURCE_HASH_CHANGED") return "原始报告不可用或已变更，请重新选择报告。"; if(code.startsWith("MODEL_") || code === "MODEL") return "模型配置或连接不可用，请检查模型设置。"; if(code === "PREVIEW_REQUIRED" || code === "STALE") return "提交预览已失效，请重新生成预览。"; if(code === "OUTPUT_EXISTS") return "输出文件已存在，请调整输出后重试。"; return "操作未完成，请检查输入后重试。";}
  async function call(name,...args){try {const value=await api[name](...args); if(value && value.ok === false) throw value; return value?.ok === true ? Object.fromEntries(Object.entries(value).filter(([key])=>key!=="ok")) : value;} catch(error){message(safeError(error),true); throw error;}}
  function step(number){["upload","extract","review","commit"].forEach((name,index)=>{const el=$("report-step-"+name); el.hidden=index+1!==number; $("report-tab-"+name).setAttribute("aria-current",index+1===number?"step":"false");});}
  function profileOptions(){const profiles=bootstrap?.profiles||[]; $("report-model-profile").innerHTML=profiles.map(p=>`<option value="${esc(p.name)}">${esc(p.name)} · ${esc(p.model)}</option>`).join("");}
  function profileDetails(){const profile=(bootstrap?.profiles||[]).find(item=>item.name===$("report-model-profile").value); $("report-model-summary").textContent=profile?`模型：${profile.name} / ${profile.model}；目标主机：${new URL(profile.base_url).hostname}`:"请选择已保存的模型配置";}
  async function chooseReport(){const item=await call("choose_report","report"); selectedReport=item.selection_token; $("report-file-name").textContent=`已选择：${item.basename}`; message("请选择评估期间和已保存模型后开始分析。");}
  async function saveProfile(){const profile={name:$("model-name").value.trim(),base_url:$("model-base-url").value.trim(),model:$("model-model").value.trim(),api_key:$("model-api-key").value,supports_vision:$("model-supports-vision").checked}; const saved=await call("save_model_profile",profile); $("model-api-key").value=""; bootstrap.profiles=(bootstrap.profiles||[]).filter(p=>p.name!==saved.profile.name).concat(saved.profile); profileOptions(); $("report-model-profile").value=saved.profile.name; profileDetails(); message("模型配置已保存；密钥不会再次显示。");}
  async function testProfile(){const result=await call("test_model_profile",$("report-model-profile").value); message(`模型连接已验证：${result.hostname}`);}
  async function start(){period=$("report-period").value.trim(); if(!selectedReport || !/^[A-Za-z0-9][A-Za-z0-9_-]{0,31}$/.test(period)){message("请先选择报告，并填写安全的评估期间。",true);return;} const result=await call("start_analysis",selectedReport,$("report-model-profile").value); taskId=result.task.task_id; $("report-extraction-method").textContent=`提取方式：${result.task.extraction_method||"本地处理"}`; step(2); await poll();}
  async function poll(){clearTimeout(pollTimer); const result=await call("get_task",taskId); const task=result.task; $("report-extraction-method").textContent=`状态：${task.status}；提取方式：${task.extraction_method||"本地处理"}`; if(terminal.has(task.status)){if(task.status==="失败"){message("本地提取失败，可重新选择报告后重试。",true);return;} findings=(await call("get_findings",taskId)).findings||[]; renderFindings(); step(3); message(`已提取 ${findings.length} 项合成发现；模型输出仅供审计判断参考。`); return;} pollTimer=setTimeout(()=>poll().catch(()=>{}),750);}
  function value(f,key){if(key==="needs_review")return f.needs_review?"true":"false"; if(dims.includes(key))return f.impact_scores?.[key]??""; return f[key]??"";}
  function formValue(){const payload={}; approved.forEach(key=>{const input=document.querySelector(`[data-finding-field="${key}"]`); let value=input?.type === "checkbox" ? input.checked : input?.value; if(dims.includes(key)) value=value===""?null:Number(value); if(key==="likelihood") value=value===""?null:Number(value); if(key==="needs_review") value=Boolean(value); payload[key]=value;}); return payload;}
  function fillForm(f){approved.forEach(key=>{const input=document.querySelector(`[data-finding-field="${key}"]`); if(!input)return; if(input.type==="checkbox")input.checked=Boolean(f[key]); else input.value=value(f,key);}); $("report-finding-form").__findingId=f.finding_id;}
  function renderFindings(){const list=$("report-findings"); list.innerHTML=findings.map(f=>`<button type="button" class="report-finding" data-finding-id="${esc(f.finding_id)}" aria-selected="${selectedIds.includes(f.finding_id)}">${esc(f.finding_id)} · ${esc(f.title)} <span class="note">${esc(f.review_status)}</span></button>`).join(""); list.querySelectorAll("[data-finding-id]").forEach(button=>button.addEventListener("click",event=>selectFinding(button.dataset.findingId,event.ctrlKey||event.metaKey))); if(findings.length&&!$("report-finding-form").__findingId)selectFinding(findings[0].finding_id,false);}
  async function selectFinding(id,multi){if(multi){selectedIds=selectedIds.includes(id)?selectedIds.filter(item=>item!==id):[...selectedIds,id];renderFindings();return;} selectedIds=[id]; const finding=findings.find(item=>item.finding_id===id); fillForm(finding); renderFindings(); try {const preview=await call("get_source_preview",taskId,id,selectedReport); $("report-source-viewer").textContent=preview.source_excerpt||"来源预览不可用";} catch(_) {$("report-source-viewer").textContent="请重新选择报告以查看来源。";}}
  function replaceSaved(items){const values=items?.findings || (items?.finding?[items.finding]:[]); values.forEach(value=>{const index=findings.findIndex(item=>item.finding_id===value.finding_id); if(index>=0)findings[index]=value;}); $("report-finding-form").__findingId=""; renderFindings();}
  async function saveFinding(status){const id=$("report-finding-form").__findingId; if(!id)return; const payload=formValue(); payload.review_status=status||payload.review_status; const result=await call("save_finding",taskId,id,payload); replaceSaved(result); message("发现已保存，仍需审计人员判断。");}
  async function merge(){if(selectedIds.length<2){message("请选择至少两项发现后合并。",true);return;} const result=await call("merge_findings",taskId,selectedIds,formValue()); findings=result.findings||findings; selectedIds=[selectedIds[0]]; renderFindings(); message("所选发现已合并；被合并项标记为排除。");}
  async function split(){const id=$("report-finding-form").__findingId; if(!id)return; const base=formValue(); const payloads=[{...base,finding_id:`${id}-A`},{...base,finding_id:`${id}-B`,title:`${base.title}（拆分）`}]; const result=await call("split_finding",taskId,id,payloads); findings=result.findings||findings; renderFindings();}
  function decisions(){return findings.map(f=>{if(f.review_status==="已排除")return {action:"exclude",finding_ids:[f.finding_id]}; const action=f.matched_risk_id?"merge":"create"; return {action,finding_ids:[f.finding_id],risk_id:f.matched_risk_id||"",name:f.title,domain:f.domain,description:f.fact_summary,owner_dept:"审计部",period,likelihood:f.likelihood,impact_scores:f.impact_scores,rationale:f.rationale,controls:[]};});}
  function renderPreview(preview){const fields=["new_risks","updated_risks","control_replacements","excluded_findings","warnings"]; $("report-preview-list").innerHTML=fields.map(key=>`<li>${key}：${esc(JSON.stringify(preview[key]||[]))}</li>`).join(""); $("report-change-preview").hidden=false;}
  async function preview(){if(!$("report-controls-confirmed").checked){message("请先明确确认当前控制措施。",true);return;} const chosen=await call("choose_report","workbook"); selectedWorkbook=chosen.selection_token; const result=await call("preview_commit",taskId,selectedWorkbook,decisions()); commitToken=result.commit_token; renderPreview(result); message("预览已生成。历史发现不证明当前剩余风险，提交前请复核。 ");}
  async function commit(){if(!commitToken)return; const button=$("report-commit"); button.disabled=true; try {const result=await call("commit_to_workbook",taskId,selectedWorkbook,decisions(),commitToken); commitToken=null; const risks=result.assessed_risks||result.risks||[]; const controls=result.controls||[]; if(!window.RAHMDesktop.loadPeriodData(period,risks,controls))throw new Error("invalid dataset"); message(`已写入：${result.workbook_path}`); $("report-output-path").textContent=`已写入：${result.workbook_path}`; document.querySelector("main").scrollIntoView({behavior:"smooth"});} catch(error){button.disabled=false;}}
  async function init(){api=window.pywebview && window.pywebview.api; if(!api)return; bootstrap=await call("get_bootstrap"); $("desktop-report-nav").hidden=false; $("desktop-report-nav").addEventListener("click",()=>{$("desktop-report-shell").hidden=false;step(1);}); profileOptions(); profileDetails(); $("report-model-profile").addEventListener("change",profileDetails); $("report-choose").addEventListener("click",()=>chooseReport().catch(()=>{})); $("report-start").addEventListener("click",()=>start().catch(()=>{})); $("model-save").addEventListener("click",()=>saveProfile().catch(()=>{})); $("model-test").addEventListener("click",()=>testProfile().catch(()=>{})); $("report-save").addEventListener("click",()=>saveFinding().catch(()=>{})); $("report-accept").addEventListener("click",()=>saveFinding("已接受").catch(()=>{})); $("report-exclude").addEventListener("click",()=>saveFinding("已排除").catch(()=>{})); $("report-merge").addEventListener("click",()=>merge().catch(()=>{})); $("report-split").addEventListener("click",()=>split().catch(()=>{})); $("report-to-commit").addEventListener("click",()=>step(4)); $("report-preview").addEventListener("click",()=>preview().catch(()=>{})); $("report-commit").addEventListener("click",()=>commit().catch(()=>{}));}
  window.addEventListener("pywebviewready",()=>init().catch(()=>{}),{once:true});
})();
